### PR TITLE
Fix bugs, update dependency and use worker middleware

### PR DESCRIPTION
**Pull request by stonechoe**
This PR contains following changes:

* use new build system: migrate to vite from CRA (Create-React-App, which is no longer actively maintained.)
* update dependency (ts 4 -> 5, react 17 -> 18, node 12 -> 20, mui 4 -> 5, etc.)
* fix keyboard shortcut bug
* fix js-step bug
* use worker middleware

### CODE REVIEW

**Comment by jhnaldo** [comment]
@stonechoe, I think the `npm start` command no longer works with this update. How can I turn it on?

**Comment by stonechoe** [comment]
@jhnaldo it works with `npm run dev`, but I just also added `npm start` in the lastest commit. it will now work.

**Comment by stonechoe** [comment]
@jhnaldo this PR is now ready for review

added changes:
* remove SharedArrayBuffer
* fix README.md
* use worker middleware

**Review by jhnaldo — APPROVED** [review]
LGTM! Thanks! 👍🏻

**Pull request merged**
